package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ---- INI parser tests -------------------------------------------------------

func TestParseINI_BasicRoundtrip(t *testing.T) {
	content := `[ServerSettings]
MaxPlayers=70
ServerPassword=secret

[SessionSettings]
SessionName=My Server
`
	tmp := writeTemp(t, content)
	doc, err := parseINI(tmp)
	if err != nil {
		t.Fatalf("parseINI: %v", err)
	}

	ss := doc.getSection("ServerSettings")
	if ss == nil {
		t.Fatal("ServerSettings section not found")
	}
	if got := ss.getValue("MaxPlayers"); got != "70" {
		t.Errorf("MaxPlayers: got %q, want %q", got, "70")
	}
	if got := ss.getValue("ServerPassword"); got != "secret" {
		t.Errorf("ServerPassword: got %q, want %q", got, "secret")
	}

	ses := doc.getSection("SessionSettings")
	if ses == nil {
		t.Fatal("SessionSettings section not found")
	}
	if got := ses.getValue("SessionName"); got != "My Server" {
		t.Errorf("SessionName: got %q, want %q", got, "My Server")
	}
}

func TestParseINI_PreservesComments(t *testing.T) {
	content := `; generated by ARK server manager
[ServerSettings]
; server password
ServerPassword=pw
`
	tmp := writeTemp(t, content)
	doc, err := parseINI(tmp)
	if err != nil {
		t.Fatalf("parseINI: %v", err)
	}

	out := filepath.Join(t.TempDir(), "out.ini")
	if err := writeINI(out, doc); err != nil {
		t.Fatalf("writeINI: %v", err)
	}

	got, _ := os.ReadFile(out)
	if !strings.Contains(string(got), "; generated by ARK server manager") {
		t.Error("comment line was lost during write")
	}
	if !strings.Contains(string(got), "; server password") {
		t.Error("inline comment line was lost during write")
	}
}

func TestSetKeyValue_UpdateExisting(t *testing.T) {
	content := "[ServerSettings]\nMaxPlayers=70\n"
	tmp := writeTemp(t, content)
	doc, _ := parseINI(tmp)

	doc.setKeyValue("ServerSettings", "MaxPlayers", "100")

	if got := doc.getSection("ServerSettings").getValue("MaxPlayers"); got != "100" {
		t.Errorf("got %q, want %q", got, "100")
	}

	// Should still be only one entry
	count := 0
	for _, l := range doc.getSection("ServerSettings").lines {
		if strings.EqualFold(l.key, "MaxPlayers") {
			count++
		}
	}
	if count != 1 {
		t.Errorf("expected 1 MaxPlayers entry, got %d", count)
	}
}

func TestSetKeyValue_AddsNewSection(t *testing.T) {
	doc := &iniDocument{}
	doc.setKeyValue("NewSection", "Key", "Val")

	s := doc.getSection("NewSection")
	if s == nil {
		t.Fatal("section not created")
	}
	if got := s.getValue("Key"); got != "Val" {
		t.Errorf("got %q, want %q", got, "Val")
	}
}

func TestDeleteKey(t *testing.T) {
	content := "[ServerSettings]\nServerPassword=pw\nMaxPlayers=70\n"
	tmp := writeTemp(t, content)
	doc, _ := parseINI(tmp)

	doc.deleteKey("ServerSettings", "ServerPassword")

	if got := doc.getSection("ServerSettings").getValue("ServerPassword"); got != "" {
		t.Errorf("expected empty after delete, got %q", got)
	}
	if got := doc.getSection("ServerSettings").getValue("MaxPlayers"); got != "70" {
		t.Error("unrelated key was removed")
	}
}

// ---- ServerConfig load/save tests -------------------------------------------

func TestSaveAndLoadServerConfig(t *testing.T) {
	dir := t.TempDir()
	cfg := DefaultServerConfig()
	cfg.DataDir = dir
	cfg.Name = "Test Server"
	cfg.MaxPlayers = 50
	cfg.ServerPassword = "pass123"
	cfg.AdminPassword = "adminpass"
	cfg.GamePort = 7778
	cfg.QueryPort = 27016
	cfg.RCONPort = 27021

	if err := SaveServerConfig(cfg); err != nil {
		t.Fatalf("SaveServerConfig: %v", err)
	}

	loaded, err := LoadServerConfig(dir)
	if err != nil {
		t.Fatalf("LoadServerConfig: %v", err)
	}

	if loaded.Name != cfg.Name {
		t.Errorf("Name: got %q, want %q", loaded.Name, cfg.Name)
	}
	if loaded.MaxPlayers != cfg.MaxPlayers {
		t.Errorf("MaxPlayers: got %d, want %d", loaded.MaxPlayers, cfg.MaxPlayers)
	}
	if loaded.ServerPassword != cfg.ServerPassword {
		t.Errorf("ServerPassword: got %q, want %q", loaded.ServerPassword, cfg.ServerPassword)
	}
	if loaded.AdminPassword != cfg.AdminPassword {
		t.Errorf("AdminPassword: got %q, want %q", loaded.AdminPassword, cfg.AdminPassword)
	}
	if loaded.GamePort != cfg.GamePort {
		t.Errorf("GamePort: got %d, want %d", loaded.GamePort, cfg.GamePort)
	}
	if loaded.QueryPort != cfg.QueryPort {
		t.Errorf("QueryPort: got %d, want %d", loaded.QueryPort, cfg.QueryPort)
	}
}

func TestLoadServerConfig_MissingFile(t *testing.T) {
	dir := t.TempDir()
	cfg, err := LoadServerConfig(dir)
	if err != nil {
		t.Fatalf("expected no error for missing ini, got: %v", err)
	}
	// Should return defaults
	if cfg.MaxPlayers != 70 {
		t.Errorf("expected default MaxPlayers=70, got %d", cfg.MaxPlayers)
	}
}

// ---- GenerateLaunchCommand tests --------------------------------------------

func TestGenerateLaunchCommand_Basic(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.Name = "My Server"
	cfg.AdminPassword = "admin"
	cmd := GenerateLaunchCommand(cfg)

	checks := []string{
		"TheIsland_WP",
		"?listen",
		"?SessionName=My Server",
		"?MaxPlayers=70",
		"?ServerAdminPassword=admin",
		"-port=7777",
		"-queryport=27015",
		"-NoBattlEye",
	}
	for _, c := range checks {
		if !strings.Contains(cmd, c) {
			t.Errorf("command missing %q\nfull cmd: %s", c, cmd)
		}
	}
}

func TestGenerateLaunchCommand_Crossplay(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.Crossplay = true
	cmd := GenerateLaunchCommand(cfg)
	if !strings.Contains(cmd, "-ServerPlatform=EpicAndSteam") {
		t.Errorf("crossplay flag missing: %s", cmd)
	}
}

func TestGenerateLaunchCommand_Mods(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.Mods = []string{"123456", "789012"}
	cmd := GenerateLaunchCommand(cfg)
	if !strings.Contains(cmd, "-mods=123456,789012") {
		t.Errorf("mods flag missing or malformed: %s", cmd)
	}
}

func TestGenerateLaunchCommand_NoPassword(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.ServerPassword = ""
	cmd := GenerateLaunchCommand(cfg)
	if strings.Contains(cmd, "ServerPassword") {
		t.Errorf("empty password should not appear in command: %s", cmd)
	}
}

func TestGenerateLaunchCommand_NoRCON(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.RCONEnabled = false
	cmd := GenerateLaunchCommand(cfg)
	if strings.Contains(cmd, "RCONEnabled") {
		t.Errorf("RCON should be absent when disabled: %s", cmd)
	}
}

// ---- ValidateConfig tests ---------------------------------------------------

func TestValidateConfig_Valid(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.AdminPassword = "admin"
	if err := ValidateConfig(cfg); err != nil {
		t.Errorf("expected no error, got: %v", err)
	}
}

func TestValidateConfig_MissingAdminPassword(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.AdminPassword = ""
	if err := ValidateConfig(cfg); err == nil {
		t.Error("expected error for missing admin password")
	}
}

func TestValidateConfig_InvalidPort(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.AdminPassword = "admin"
	cfg.GamePort = 0
	if err := ValidateConfig(cfg); err == nil {
		t.Error("expected error for port 0")
	}
}

func TestValidateConfig_PortConflict(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.AdminPassword = "admin"
	cfg.GamePort = 7777
	cfg.QueryPort = 7777
	if err := ValidateConfig(cfg); err == nil {
		t.Error("expected error for identical game/query port")
	}
}

func TestValidateConfig_MaxPlayersOutOfRange(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.AdminPassword = "admin"
	cfg.MaxPlayers = 0
	if err := ValidateConfig(cfg); err == nil {
		t.Error("expected error for MaxPlayers=0")
	}

	cfg.MaxPlayers = 256
	if err := ValidateConfig(cfg); err == nil {
		t.Error("expected error for MaxPlayers=256")
	}
}

func TestValidateConfig_MissingMap(t *testing.T) {
	cfg := DefaultServerConfig()
	cfg.AdminPassword = "admin"
	cfg.Map = ""
	if err := ValidateConfig(cfg); err == nil {
		t.Error("expected error for empty map")
	}
}

// ---- helpers ----------------------------------------------------------------

func writeTemp(t *testing.T, content string) string {
	t.Helper()
	tmp := filepath.Join(t.TempDir(), "test.ini")
	if err := os.WriteFile(tmp, []byte(content), 0644); err != nil {
		t.Fatalf("writeTemp: %v", err)
	}
	return tmp
}
